"""Initial baseline migration

Revision ID: ba124bb415d6
Revises: 
Create Date: 2026-06-15 18:50:57.218401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba124bb415d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_actor_user_id'), 'auditlog', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_auditlog_actor_username'), 'auditlog', ['actor_username'], unique=False)
    op.create_index(op.f('ix_auditlog_created_at'), 'auditlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditlog_target_type'), 'auditlog', ['target_type'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_field_name'), 'citation', ['field_name'], unique=False)
    op.create_index(op.f('ix_citation_member_id'), 'citation', ['member_id'], unique=False)
    op.create_index(op.f('ix_citation_source_id'), 'citation', ['source_id'], unique=False)
    op.create_table('familygroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_kicker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('root_member_id', sa.Integer(), nullable=True),
    sa.Column('primary_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familygroup_is_active'), 'familygroup', ['is_active'], unique=False)
    op.create_index(op.f('ix_familygroup_is_primary'), 'familygroup', ['is_primary'], unique=False)
    op.create_index(op.f('ix_familygroup_name'), 'familygroup', ['name'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('former_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('courtesy_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('art_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('childhood_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('generation_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rank_no', sa.Integer(), nullable=True),
    sa.Column('rank_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_core_member', sa.Boolean(), nullable=True),
    sa.Column('birth_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_calendar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_lunar_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_is_leap_month', sa.Boolean(), nullable=True),
    sa.Column('birth_date_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('death_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('death_calendar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('death_lunar_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('death_is_leap_month', sa.Boolean(), nullable=True),
    sa.Column('death_date_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('death_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('residence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ancestral_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('burial_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('burial_lat', sa.Float(), nullable=True),
    sa.Column('burial_lng', sa.Float(), nullable=True),
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_living', sa.Boolean(), nullable=True),
    sa.Column('spouse_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spouse_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('children_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('marriage_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('marriage_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('biography', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('privacy_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_family_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_generation'), 'member', ['generation'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    op.create_index(op.f('ix_member_primary_family_id'), 'member', ['primary_family_id'], unique=False)
    op.create_index(op.f('ix_member_privacy_level'), 'member', ['privacy_level'], unique=False)
    op.create_table('memberfamilylink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberfamilylink_family_id'), 'memberfamilylink', ['family_id'], unique=False)
    op.create_index(op.f('ix_memberfamilylink_is_primary'), 'memberfamilylink', ['is_primary'], unique=False)
    op.create_index(op.f('ix_memberfamilylink_member_id'), 'memberfamilylink', ['member_id'], unique=False)
    op.create_index(op.f('ix_memberfamilylink_relation_type'), 'memberfamilylink', ['relation_type'], unique=False)
    op.create_table('reviewrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('target_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diff_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewrequest_actor_user_id'), 'reviewrequest', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_reviewrequest_actor_username'), 'reviewrequest', ['actor_username'], unique=False)
    op.create_index(op.f('ix_reviewrequest_created_at'), 'reviewrequest', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviewrequest_member_id'), 'reviewrequest', ['member_id'], unique=False)
    op.create_index(op.f('ix_reviewrequest_status'), 'reviewrequest', ['status'], unique=False)
    op.create_table('sitesetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sourcerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repository', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sourcerecord_source_type'), 'sourcerecord', ['source_type'], unique=False)
    op.create_index(op.f('ix_sourcerecord_title'), 'sourcerecord', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('userfamilyrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userfamilyrole_family_id'), 'userfamilyrole', ['family_id'], unique=False)
    op.create_index(op.f('ix_userfamilyrole_role'), 'userfamilyrole', ['role'], unique=False)
    op.create_index(op.f('ix_userfamilyrole_user_id'), 'userfamilyrole', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userfamilyrole_user_id'), table_name='userfamilyrole')
    op.drop_index(op.f('ix_userfamilyrole_role'), table_name='userfamilyrole')
    op.drop_index(op.f('ix_userfamilyrole_family_id'), table_name='userfamilyrole')
    op.drop_table('userfamilyrole')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sourcerecord_title'), table_name='sourcerecord')
    op.drop_index(op.f('ix_sourcerecord_source_type'), table_name='sourcerecord')
    op.drop_table('sourcerecord')
    op.drop_table('sitesetting')
    op.drop_index(op.f('ix_reviewrequest_status'), table_name='reviewrequest')
    op.drop_index(op.f('ix_reviewrequest_member_id'), table_name='reviewrequest')
    op.drop_index(op.f('ix_reviewrequest_created_at'), table_name='reviewrequest')
    op.drop_index(op.f('ix_reviewrequest_actor_username'), table_name='reviewrequest')
    op.drop_index(op.f('ix_reviewrequest_actor_user_id'), table_name='reviewrequest')
    op.drop_table('reviewrequest')
    op.drop_index(op.f('ix_memberfamilylink_relation_type'), table_name='memberfamilylink')
    op.drop_index(op.f('ix_memberfamilylink_member_id'), table_name='memberfamilylink')
    op.drop_index(op.f('ix_memberfamilylink_is_primary'), table_name='memberfamilylink')
    op.drop_index(op.f('ix_memberfamilylink_family_id'), table_name='memberfamilylink')
    op.drop_table('memberfamilylink')
    op.drop_index(op.f('ix_member_privacy_level'), table_name='member')
    op.drop_index(op.f('ix_member_primary_family_id'), table_name='member')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_generation'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_familygroup_name'), table_name='familygroup')
    op.drop_index(op.f('ix_familygroup_is_primary'), table_name='familygroup')
    op.drop_index(op.f('ix_familygroup_is_active'), table_name='familygroup')
    op.drop_table('familygroup')
    op.drop_index(op.f('ix_citation_source_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_member_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_field_name'), table_name='citation')
    op.drop_table('citation')
    op.drop_index(op.f('ix_auditlog_target_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_created_at'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_actor_username'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_actor_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
